travis:
  secure:
    BINSTAR_TOKEN: YUMQMRWJhs4i9TvMzscOjj6bSBPAtto226Dcu5hDOJDzSIPXiCpT6ldjoFfPqdOpMTwBRKFfWy78qtz5YuSP1QJnutARCivQlq6OGlS367S3N0J7Fzm7hD8xVecmuf1GHyO02i7HvPXgv32xAMTbHPPxx5wkPnAJFlZlkOGbFw8N0rWZLsHxYukbDadBNCP6XLRdtbaQw0+k4/L2k/rVokWI7yMEnbyx4Vu8ZRedka88NmnumSl+NltokUsfquxbxYjOm8MlZI3UlFo7TFDRA+W2Rg+hqFFwZ4rYhzLafs3lYRZTjoZm71p6gC30SeKIweSb/QkN1sLa8UbtNNfX0Wb1omFkKDT00hxqKLJhm2KSmz6zVXKYrHIc87BwbycksV25wvHN5uUaR1kraF2M4lz32UqqD1QnfWhsZrm1kx1Sj1RQJ9P19UMeBr3E8Hsg/2xkDsALRxhSaQlMOS995CDfsQFiX20VA7214b8zHu8rYhwu2fpID6SpbsF9QX2kYhfJUoj8JKPtVlXPCA7J2oVdi5FErrXO2+ByQBokLRItTiOxFZkHPA6Chh48+0ZiKyqrNCMYnXm89xXymEU5cuC58tqK5uoAp86+0M/7rCN8VQO3CZOyDVP4FwNLav5HMO0v86jhbDdkh5tjv6F88s5SSrmybLfFpdgPwXmpoxk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
