travis:
  secure:
    BINSTAR_TOKEN: HYlfbqubJaIYMnfdlLkMHncF/MmF+iLaYyxclRK+jkocMODt72AjEmRwrYCgCZPoFXZx4hYkkJ/yRWUmOEYY9au+XCg8+Fkpcid4pLbFvxzcFzBXRtoTFKPRIPXZsxdrAg+3gJ6NoIrz7V5ktUhyWJIz8uVKgTMVFfOJxvLqjRsQFLH0t3N6uo80DpqefjQIhBXxI7eSPKNfWkpWBxoTNEraoZP9tSyfwzB16tj/QGL2yWqJtsRnB2q6rjePAhUhhuTY9IEmmSDQsxJ8fPvhMInI0CK/yd+B6YDmtwJP1eJ70pFZ526O9nOsFbv+D19s7qobuHFKDudegYbNrwn58CqeCHFlmPCkjmDRMqj2FmCLGUS5Xda6w8K+v+gYEBZ71pFSWqKwz5B73UOQ9dFGqurKL8gqavP1j+8pn+ChAbr/OHJuEATArRPRWCNbx2Um/8GzADaLh0lQjVBIeMEhBsVVRHzZbAoY6fIvW3U/gMVL5gqIzq1UIYzMq6lfCV7jSR83G0vINJh2kZEAJ6mbbQuSRxgNs78uvnsM+gGRhYCWophhCsQblJ4qtgToTekR96d1BOU0tgmLc85XVzhMQYkTAyjpiGSyFqfafHsRT5raBWczWBSBgjNjxQ+97kqUBRrtg5MZycGYTwoFhStIy0GzpVtkMXeDSoMLUbeU1rs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
